export const LOGGED_USER_DATA_LOADING = 'LOGGED_USER_DATA_LOADING';
export const LOGGED_USER_DATA_SUCCESS = 'LOGGED_USER_DATA_SUCCESS';
export const LOGGED_USER_DATA_ERROR = 'LOGGED_USER_DATA_ERROR';
export const GET_USER_DETAILS_LOADING = 'GET_USER_DETAILS_LOADING';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR';
